{
 "title": "Adaptive Concurrency",
 "time": { "from": "now-30s", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Request Rates", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Success Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(ad_http_response{response=\"200\"}[$__range])) without (response) / sum(rate(ad_http_response[$__range])) without (response)",
     "legendFormat": "{{tenant}}"
    }
   ]
  },
  {
   "title": "Responses per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "rate(ad_http_response[$__range])",
     "legendFormat": "{{tenant}} {{response}}"
    },
    { "legendFormat": "__auto" }
   ]
  },
  { "title": "Tenant Limits", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Concurrency Limit Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "ad_tenant_busy_count / ad_tenant_limit",
     "legendFormat": "{{tenant}}"
    }
   ]
  },
  {
   "title": "Tenant Limits",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    { "expr": "ad_tenant_limit", "legendFormat": "{{tenant}}" }
   ]
  },
  { "title": "Concurrency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Concurrent Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "targets": [
    { "expr": "ad_concurrent_requests", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "CPU Time Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "ad_cpu_time_used / (ad_cpu_time_used + ad_cpu_time_remaining)"
    }
   ]
  }
 ]
}