{
 "title": "Adaptive Concurrency",
 "time": { "from": "now-30s", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Request Rates", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Success Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(ad_http_response{response=\"200\"}[$__range])) without (response) / sum(rate(ad_http_response[$__range])) without (response)",
     "legendFormat": "{{client}}"
    }
   ]
  },
  {
   "title": "Responses Per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "rate(ad_http_response[$__range])",
     "legendFormat": "{{client}} {{response}}"
    },
    { "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Average RTT",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(rate(ad_http_rtt[$__range])) / sum(rate(ad_http_response[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Concurrency Limits", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Client Concurrency Limits",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    { "expr": "ad_client_limit", "legendFormat": "{{client}}" }
   ]
  },
  {
   "title": "Concurrency Limit Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "ad_client_concurrency / ad_client_limit",
     "legendFormat": "{{client}}"
    }
   ]
  },
  { "title": "CPU Concurrency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Concurrent Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "targets": [
    { "expr": "ad_concurrent_requests", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "CPU Time Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "ad_cpu_time_used / (ad_cpu_time_used + ad_cpu_time_remaining)"
    }
   ]
  }
 ]
}